# coding=utf-8
"""FIRECODE: Filtering Refiner and Embedder for Conformationally Dense Ensembles
Copyright (C) 2021-2026 Nicolò Tampellini

SPDX-License-Identifier: LGPL-3.0-or-later

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with this program. If not, see
https://www.gnu.org/licenses/lgpl-3.0.en.html#license-text.

"""

from __future__ import annotations

import os
from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Any, Iterable, cast

from firecode.typing_ import MaybeNone
from firecode.utils import str_to_var

if TYPE_CHECKING:
    from firecode.embedder import Embedder

# Known keywords and relative priority level:
# 1 : First to run, set some option
# 2 : Second to run, modify variables, dependence on priority 1 options
# 3 : Third to run, modify variables, dependence on priority 2 options

keywords_dict = {
    "BYPASS": 1,  # Debug keyword. Used to skip all pruning steps and
    # directly output all the embedded geometries.
    "C": 1,  # concentration, in mol/L
    "CALC": 1,  # Manually overrides the calculator in "settings.py"
    "CHARGE": 1,  # Specifies charge for the embedding
    "CONC": 1,  # concentration, in mol/L
    "CONFS": 1,  # Maximum number of conformers generated by csearch
    "CLASHES": 1,  # Manually specify the max number of clashes and/or
    # the distance threshold at which two atoms are considered
    # clashing. The more forgiving, the more structures will reach
    # the geometry optimization step. Syntax: `CLASHES(num=3,dist=1.2)`
    "NCI": 1,  # applies ellipsoid potential in CREST and GOAT runs.
    "CRESTLEVEL": 1,  # level of the CREST run
    "DEEP": 1,  # Performs a deeper search, retaining more starting points
    # for calculations and smaller turning angles.
    "DEBUG": 1,  # DEBUG KEYWORD. Writes more stuff to file.
    "DIST": 2,  # Manually imposed distance between specified atom pairs,
    # in Angstroms. Syntax uses parenthesis and commas:
    # `DIST(a=2.345,b=3.67,c=2.1)`
    "DRYRUN": 1,  # skip any computing step - used to check for runtime errors during setup)
    # 'ENANTIOMERS',    # Do not discard enantiomeric structures.
    "EZPROT": 1,  # Double bond protection
    "FFOPT": 1,  # Manually turn on ``FF=ON`` or off ``FF=OFF`` the force
    # field optimization step, overriding the value in ``settings.py``.
    "FREQ": 1,  # Run frequency calculation after geometry optimization.
    "IMAGES": 1,  # Number of images to be used in neb>/NEB jobs
    "KCAL": 1,  # Trim output structures to a given value of relative energy.
    # Syntax: `KCAL=n`, where n can be an integer or float.
    "LET": 1,  # Overrides safety checks that prevent the
    # program from running too large calculations
    "LEVEL": 1,  # Manually set the theory level to be used.
    # . Syntax: `LEVEL(PM7_EPS=6.15)
    "MULT": 1,  # Set global multiplicity.
    "NEB": 2,  # Base keyword to specify options for the neb> operator.
    "NEWBONDS": 1,  # Manually specify the maximum number of "new bonds" that a
    # TS structure can have to be retained and not to be considered
    # scrambled. Default is 1. Syntax: `NEWBONDS=1`
    "NOOPT": 1,  # Skip the optimization steps, directly writing structures to file.
    "ONLYREFINED": 1,  # Discard structures that do not successfully refine bonding distances.
    "P": 1,  # Pressure, in atmospheres.
    "PKA": 1,  # Set reference pKa for a specific compound
    "REFINE": 1,  # Same as calling refine> on a single file
    "RMSD": 1,  # RMSD threshold (Angstroms) for structure pruning. The smaller,
    # the more retained structures. Default is 0.5 A.
    # Syntax: `RMSD=n`, where n is a number.
    "ROTRANGE": 1,  # Does not apply to "string" embeds. Manually specify the rotation
    # range to be explored around the structure pivot.
    # Default is 120. Syntax: `ROTRANGE=120`
    "SCRAMBLECHECK": 1,  # After optimization, check that the structure did not scramble.
    "SHRINK": 1,  # Exaggerate orbital dimensions during embed, scaling them by a factor
    # of one and a half. This makes it easier to perform the embed without
    # having molecules clashing one another. Then, the correct distance between
    # reactive atom pairs is achieved as for standard runs by spring constraints
    # during MOPAC/ORCA optimization.
    "SIMPLEORBITALS": 1,  # Override the automatic orbital assignment, using "Single" type orbitals for
    # every reactive atom
    "SOLVENT": 1,  # set the solvation model
    "STEPS": 1,  # Manually specify the number of steps to be taken in scanning rotations.
    # For string embeds, the range to be explored is the full 360°, and the
    # default `STEPS=24` will perform 15° turns. For cyclical and chelotropic
    # embeds, the rotation range to be explored is +-`ROTRANGE` degrees.
    # Therefore, the default value of `ROTRANGE=120 STEPS=12` will perform
    # twelve 20 degrees turns.
    "SUPRAFAC": 1,  # Only retain suprafacial orbital configurations in cyclical TSs.
    # Thought for Diels-Alder and other cycloaddition reactions.
    "T": 1,  # Set temperature, in Kelvin. Syntax: `T=300`
    "T_C": 1,  # Set temperature, in Celsius. Syntax: `T_C=27`
}


def get_keyword_suggestion(unknown_kw: str) -> str | None:
    """Given an unknown keyword, return the known one
    with the highest score, if similar enough,
    else return None.
    """
    scores_tuples = [(kw, kw_similarity_score(kw, unknown_kw)) for kw in keywords_dict.keys()]
    best_match, best_score = sorted(scores_tuples, key=lambda x: x[1], reverse=True)[0]

    if best_score > 0.5:
        return best_match

    return None


def kw_similarity_score(ref: str, kw: str) -> float:  # pragma: no cover
    """Simple scoring for string similarity"""
    score = 0
    letters = []
    for letter in kw:
        if letter not in letters:
            score += ref.count(letter)
            letters.append(letter)

    return score / len(ref)


@dataclass
class NEBOptions:
    """Simple dataclass with truthy behavior."""

    n_images: int
    preopt: bool
    climbing_image: bool

    def __bool__(self) -> bool:
        return True


@dataclass
class Options:
    # only used by cyclical embeds, can be set here
    rotation_range: int = 45

    # Set later by the _setup() function based on embed type,
    # since it is used by both cyclical and string embeds
    rotation_steps: int | MaybeNone = None
    custom_rotation_steps: int | None = None

    rmsd: float = 0.5
    rigid: bool = False
    max_confs: int = 1000

    max_clashes: int = 0
    clash_thresh: float = 1.5

    max_newbonds: int = 0

    optimization: bool = True
    freq: bool = False
    calculator: str = str(os.environ.get("FIRECODE_CALCULATOR"))
    theory_level: str | MaybeNone = None  # set later in _calculator_setup()
    solvent: str | MaybeNone = None
    scramble_check: bool = False
    charge: int = 0
    mult: int = 1
    T: float = 298.15  # in K
    P: float | None = None  # in atm
    C: float = 0.1  # in mol/L

    nci: bool = False
    crestlevel: str | None = None
    shrink: bool = False
    shrink_multiplier: float = 1.0
    suprafacial: bool = False
    simpleorbitals: bool = False
    only_refined: bool = False
    double_bond_protection: bool = False
    keep_hb: bool = False
    dryrun: bool = False
    checkpoint_frequency: int = 50
    images: int | None = None

    fix_angles_in_deformation: bool = False
    # Not possible to set manually through a keyword.
    # Monomolecular embeds have it on to prevent
    # scrambling, but better to leave it off for
    # less severe deformations, since convergence
    # is faster

    kcal_thresh: float = 10.0
    pka_ref: tuple[str, float] | None = None
    bypass: bool = False
    debug: bool = False
    let: bool = False
    check_structures: bool = False
    noembed: bool = False
    # Default values, updated if _parse_input
    # finds keywords and calls _set_options

    operators: list[str] = field(default_factory=list)
    # this list will be filled with operator strings
    # that need to be exectured before the run. i.e. ['firecode_search>mol.xyz']

    operators_dict: dict[int, list[str]] = field(default_factory=dict)
    # Analogous dictionary that will contain the seuquences of operators for each molecule

    single_thread: bool = cast(
        "bool", str_to_var(os.environ.get("FIRECODE_FORCE_SINGLE_THREAD", ""))
    )
    # enforce the use of a single thread in multimolecular optimization

    md_data: dict[str, Any] = field(default_factory=dict)
    # data for and from MD simulations

    def __repr__(self) -> str:
        d = {var: self.__getattribute__(var) for var in dir(self) if var[0] != "_"}

        repr_if_true = (
            "bypass",
            "check_structures",
            "nci",
            "debug",
            "let",
            "freq",
            "ts",
            "noembed",
            "keep_hb",
            "operators",
            "keep_hb",
            "dryrun",
            "shrink",
            "rigid",
            "scramble_check",
            "suprafacial",
            "simpleorbitals",
            "fix_angles_in_deformation",
            "double_bond_protection",
        )

        for name in repr_if_true:
            if not d.get(name, True):
                d.pop(name)

        repr_if_not_none = (
            "kcal_thresh",
            "solvent",
            "pka_ref",
            "images",
        )

        for name in repr_if_not_none:
            if d[name] is None:
                d.pop(name)

        padding = 1 + max([len(key) for key in d.keys()])

        return "\n".join(
            [f"{key}{' ' * (padding - len(key))}: {value}" for key, value in d.items()]
        )

    def _init_neb_options(self) -> None:
        """Initialize NEB options."""
        self.neb = NEBOptions(
            n_images=self.images if self.images is not None else 7,
            preopt=True,
            climbing_image=True,
        )


class Option_setter:
    def __init__(self, embedder: Embedder, *args: Any) -> None:
        embedder.kw_line = embedder.kw_line if hasattr(embedder, "kw_line") else ""

        self.keywords = [
            word.split("=")[0].upper() if "(" not in word else word.split("(")[0].upper()
            for word in embedder.kw_line.split()
        ]

        self.kws_raw = [k.upper() for k in embedder.kw_line.split()]
        self.kw_table = {
            kw: rawstring for kw, rawstring in zip(self.keywords, self.kws_raw, strict=True)
        }

        self.kws_raw_case_sensitive = embedder.kw_line.split()
        self.kw_table_case_sens = {
            kw: rawstring
            for kw, rawstring in zip(self.keywords, self.kws_raw_case_sensitive, strict=True)
        }

        self.embedder = embedder
        self.args = args

        for k in self.keywords:
            if k not in keywords_dict.keys():
                guess = get_keyword_suggestion(k)
                extra = "" if guess is None else f' Did you mean "{guess}"?'
                raise SyntaxError(
                    f'Keyword "{k}" was not understood. Please check your syntax.{extra}'
                )

        if self.kws_raw:
            embedder.log(
                "\n--> Parsed keywords, in order of execution:\n    "
                + " ".join(self.sorted_keywords())
                + "\n"
            )

    def _refine_operator_routine(self) -> None:
        if len(self.embedder.objects) > 1:
            raise SystemExit(
                (
                    "The refine> operator can only be used with one multimolecular file per run, "
                    f"in .xyz format. ({len(self.embedder.objects)} files found in input)"
                )
            )

        self.embedder._set_embedder_structures_from_mol()

        if self.embedder.options.rmsd is None:
            # set this only if user did not already specify a value
            self.embedder.options.rmsd = 0.25

        self.embedder.objects[0].compute_orbitals(
            override="Single" if self.embedder.options.simpleorbitals else None
        )
        self.embedder.options.noembed = True

    def bypass(self, options: Options, *args: Any) -> None:
        options.bypass = True
        options.optimization = False

    def charge(self, options: Options, *args: Any) -> None:
        kw = self.kw_table["CHARGE"]
        options.charge = int(kw.split("=")[1])

    def mult(self, options: Options, *args: Any) -> None:
        kw = self.kw_table["MULT"]
        options.mult = int(kw.split("=")[1])

    def confs(self, options: Options, *args: Any) -> None:
        kw = self.kw_table["CONFS"]
        options.max_confs = int(kw.split("=")[1])

    def crestnci(self, options: Options, *args: Any) -> None:
        options.nci = True

    def nci(self, options: Options, *args: Any) -> None:
        options.nci = True

    def dryrun(self, options: Options, *args: Any) -> None:
        options.dryrun = True

    def suprafac(self, options: Options, *args: Any) -> None:
        options.suprafacial = True

    def deep(self, options: Options, *args: Any) -> None:
        options.rmsd = 0.1
        options.rotation_steps = 72
        options.max_clashes = 1
        options.clash_thresh = 1.4

    def rotrange(self, options: Options, *args: Any) -> None:
        kw = self.kw_table["ROTRANGE"]
        options.rotation_range = int(kw.split("=")[1])

    def steps(self, options: Options, *args: Any) -> None:
        kw = self.kw_table["STEPS"]
        options.custom_rotation_steps = int(kw.split("=")[1])

    def rmsd(self, options: Options, *args: Any) -> None:
        kw = self.kw_table["RMSD"]
        options.rmsd = float(kw.split("=")[1])

    def noopt(self, options: Options, *args: Any) -> None:
        options.optimization = False

    def images(self, options: Options, *args: Any) -> None:
        kw = self.kw_table["IMAGES"]
        options.images = int(kw.split("=")[1])

    def dist(self, options: Options, *args: Any) -> None:
        kw = self.kw_table_case_sens["DIST"]
        orb_string = kw[5:-1].replace(" ", "")
        # orb_string looks like 'a=2.345,b=3.456,c=2.22'

        embedder = args[0]
        embedder._set_custom_orbs(orb_string)

    def clashes(self, options: Options, *args: Any) -> None:
        kw = self.kw_table["CLASHES"]
        clashes_string = kw[8:-1].lower().replace(" ", "")
        # clashes_string now looks like 'num=3,dist=1.2'

        for piece in clashes_string.split(","):
            s = piece.split("=")
            if s[0].lower() == "num":
                options.max_clashes = int(s[1])
            elif s[0].lower() == "dist":
                options.clash_thresh = float(s[1])
            else:
                raise SyntaxError(
                    (
                        f"Syntax error in CLASHES keyword -> CLASHES({clashes_string})."
                        + "Correct syntax looks like: CLASHES(num=3,dist=1.2)"
                    )
                )

    def newbonds(self, options: Options, *args: Any) -> None:
        kw = self.kw_table["NEWBONDS"]
        options.max_newbonds = int(kw.split("=")[1])

    def neb(self, options: Options, *args: Any) -> None:
        options._init_neb_options()

        kw = self.kw_table["NEB"]
        neb_options_string = kw[4:-1].lower().replace(" ", "")
        # neb_options_string now looks like 'images=8,preopt=true' or ''

        if neb_options_string != "":
            for piece in neb_options_string.split(","):
                kw_name, value = piece.split("=")
                if kw_name == "images":
                    options.neb.n_images = int(value)
                elif piece == "preopt=false":
                    options.neb.preopt = False
                elif piece == "ci=false":
                    options.neb.climbing_image = False
                else:
                    raise SyntaxError(
                        (
                            f"Syntax error in NEB keyword -> NEB({neb_options_string}). "
                            + "Correct syntax looks like: NEB(images=7, preopt=true, ci=false)"
                        )
                    )
        self.embedder.log(f"--> Set NEB options: {options.neb}")

    def level(self, options: Options, *args: Any) -> None:
        kw = self.kw_table["LEVEL"]
        options.theory_level = kw.split("=")[1].upper().replace("_", " ")

        options.theory_level = options.theory_level.replace("[", "(").replace("]", ")")
        # quick fix for testing: allows the use of square brackets
        # in place of round, so that the LEVEL keyword is not
        # mistaken for one with sub-arguments. To be better addressed
        # when/if a major rewrite of the option setting happens.

        self.embedder.log(f"--> Set LEVEL to {options.theory_level}")

    def onlyrefined(self, options: Options, *args: Any) -> None:
        options.only_refined = True

    def let(self, options: Options, *args: Any) -> None:
        options.let = True

    def check(self, options: Options, *args: Any) -> None:
        options.check_structures = True

    def simpleorbitals(self, options: Options, *args: Any) -> None:
        options.simpleorbitals = True

    def kcal(self, options: Options, *args: Any) -> None:
        kw = self.kw_table["KCAL"]
        options.kcal_thresh = float(kw.split("=")[1])
        self.embedder.log(f"--> Set KCAL to {options.kcal_thresh!s}")

    def shrink(self, options: Options, *args: Any) -> None:
        options.shrink = True
        kw = self.kw_table["SHRINK"]

        parsed = kw.split("=")
        options.shrink_multiplier = float(parsed[1]) if len(parsed) > 1 else 1.5

    # def enantiomers(self, options: Options, *args: Any) -> None:
    #     options.keep_enantiomers = True

    def debug(self, options: Options, *args: Any) -> None:
        options.debug = True

        # open a dedicated debug logfile
        debug_log_filename = f"firecode_{self.embedder.stamp}_debug.log"
        self.embedder.debug_logfile = open(debug_log_filename, "a", buffering=1, encoding="utf-8")

        from logging import basicConfig

        basicConfig(filename=debug_log_filename, filemode="a")

    def ezprot(self, options: Options, *args: Any) -> None:
        options.double_bond_protection = True

    def calc(self, options: Options, *args: Any) -> None:
        kw = self.kw_table["CALC"]
        options.calculator = kw.split("=")[1]
        self.embedder.log(f"--> Set CALC to {options.calculator}")

    def solvent(self, options: Options, *args: Any) -> None:
        from firecode.solvents import solvent_synonyms

        kw = self.kw_table["SOLVENT"]
        solvent = kw.split("=")[1].lower()
        options.solvent = solvent_synonyms.get(solvent, solvent)
        self.embedder.log(f"--> Set SOLVENT to {options.solvent}")

    def pka(self, options: Options, *args: Any) -> None:
        kw = self.kw_table_case_sens["PKA"]
        pka_string, pka = kw.split("=")
        molname = pka_string[4:-1].replace(" ", "")

        if molname in [mol.filename for mol in self.embedder.objects]:
            if any(
                [f"pka>{molname}" in op.replace(" ", "") for op in self.embedder.options.operators]
            ):
                self.embedder.options.pka_ref = (molname, float(pka))
                return

        raise SyntaxError(
            f"{molname} must be present in the molecule lines, along with the pka> operator. Syntax: pka(mol.xyz)=n"
        )

    def crestlevel(self, options: Options, *args: Any) -> None:
        kw = self.kw_table["CRESTLEVEL"]
        options.crestlevel = kw.split("=")[1]
        self.embedder.log(f"--> Set CREST level to {options.crestlevel}")

    def scramblecheck(self, options: Options, *args: Any) -> None:
        options.scramble_check = True

    def t(self, options: Options, *args: Any) -> None:
        kw = self.kw_table["T"]
        options.T = float(kw.split("=")[1])
        self.embedder.log(f"--> Set temperature to {options.T:.2f} K ({options.T - 273.15:.2f} °C)")

    def t_c(self, options: Options, *args: Any) -> None:
        kw = self.kw_table["T_C"]
        options.T = float(kw.split("=")[1]) + 273.15
        self.embedder.log(f"--> Set temperature to {options.T:.2f} K ({options.T - 273.15:.2f} °C)")

    def p(self, options: Options, *args: Any) -> None:
        kw = self.kw_table["P"]
        options.P = float(kw.split("=")[1])
        self.embedder.log(
            f"--> Set pressure to {options.P:.1f} atm and global reference state to gas."
        )

    def c(self, options: Options, *args: Any) -> None:
        kw = self.kw_table["C"]
        options.C = float(kw.split("=")[1])
        self.embedder.log(
            f"--> Set concentration to {options.C:.1f} mol/L and global reference state to solution."
        )

    def conc(self, options: Options, *args: Any) -> None:
        kw = self.kw_table["CONC"]
        options.C = float(kw.split("=")[1])
        self.embedder.log(
            f"--> Set concentration to {options.C:.1f} mol/L and global reference state to solution."
        )

    def freq(self, options: Options, *args: Any) -> None:
        options.freq = True
        self.embedder.log(
            "--> FREQ keyword: will run a freqency calculation for each structure after refinement."
        )

    def set_options(self) -> None:
        for kw in self.sorted_keywords():
            setter_function = getattr(self, kw.lower())
            setter_function(self.embedder.options, self.embedder, *self.args)

        if (
            any("refine>" in op for op in self.embedder.options.operators)
            or self.embedder.options.noembed
        ):
            self._refine_operator_routine()

    def sorted_keywords(self) -> Iterable[str]:
        """Returns all the keywords sorted in the optimal execution order."""
        return sorted(self.keywords, key=lambda kw: keywords_dict.get(kw, 3))
